docker

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -1,39 +1,66 @@
-# 阶段1：构建阶段
-FROM node:16 as builder
+FROM node:18-alpine AS base
 
-# 设置工作目录
-WORKDIR /usr/src/app
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-# 复制package.json和package-lock.json
-COPY package*.json ./
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
-# 安装所有依赖项（包括开发依赖项）
-RUN npm install
 
-# 复制源代码到工作目录
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-# 构建应用程序（如果有构建脚本的话）
-RUN npm run build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# 阶段2：生产阶段
-FROM node:16-slim
+RUN yarn build
 
-# 设置工作目录
-WORKDIR /usr/src/app
+# If using npm comment out above and use below instead
+# RUN npm run build
 
-# 仅复制阶段1中构建的生产依赖项
-COPY --from=builder /usr/src/app/package*.json ./
-RUN npm install --only=production
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
 
-# 从构建阶段复制构建后的代码到当前工作目录
-COPY --from=builder /usr/src/app/dist ./dist
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
 
-# 如果你的应用程序绑定在其他端口，你需要修改这个值
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
 
-# 定义运行时的环境变量
-ENV NODE_ENV production
+ENV PORT 3000
+# set hostname to localhost
+ENV HOSTNAME "0.0.0.0"
+ENV CUR_ENV "prod"
 
-# 运行应用程序
-CMD ["node", "dist/app.js"]
+CMD ["node", "server.js"]
